### ISSUE TITLE
Installing 0.13.0 fails

### ISSUE THREAD

**Issue by BBosman** [jdanyow/aurelia-breeze#21]
Installation using `jspm install npm:aurelia-breeze` fails with the following error:

``` console
Looking up npm:aurelia-breeze
     Updating registry cache...
     Downloading npm:aurelia-breeze@0.13.0

warn Error on processPackageConfig
     Package.json dependency aurelia-binding set to npm:aurelia-binding@^1.0.0-beta.1, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for npm:aurelia-breeze.
         at /Users/BBosman/Development/ExternalApps/Aurelia/node_modules/systemjs-builder/lib/builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (/Users/BBosman/Development/ExternalApps/Aurelia/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/Users/BBosman/Development/ExternalApps/Aurelia/node_modules/rsvp/dist/rsvp.js:779:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error processing package config for npm:aurelia-breeze.

warn Installation changes not saved.
```

**Comment by jdanyow** [comment]
sorry about that- I'm getting the plugins cut-over to npm, will have this fixed by tomorrow afternoon

**Comment by jdanyow** [comment]
this is fixed
